export const FIX_TEXT = "JAHESH";

export const OPCODE = {
  DEVICE_STATUS: "01",
  RELAY_STATUS: "02",
  SMS_LANGUAGE: "03",
  PHONES: "04",
  PHONES_SETTINGS: "05",
  PHONES_LIST: "06",
  TIME_SETTINGS: "07",
  ALARM_PERIOD: "08",
  ALARM_STATUS: "09",
  SYSTEM_MODE: "10",
  TEST: "11",
  DOUBLE_SECURE: "12",
  PASSWORD_MENU: "13",
  PASSWORD_SMS: "14",
  ZONES_SETTINGS: "15",
  OUTPUT_SETTINGS: "16",
};
